version: '3.5'
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_poc
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: poc_type_orm
    ports:
      - 3316:3306
    volumes:
      #- db-config:/etc/mysql
      #- db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    networks:
      - poc
    cap_add:
      - SYS_NICE

networks:
  poc:
    external:
      name: poc_nw
